USE ROLE ACCOUNTADMIN;

CREATE SCHEMA IF NOT EXISTS NORA_PACKAGE;

CREATE OR REPLACE TABLE NORA_PACKAGE.SUBSCRIBER_OPERATIONAL_DATA (
    subscriber_id VARCHAR,
    provision_status VARCHAR,
    package VARCHAR
);

CREATE OR REPLACE STAGE NORA_PACKAGE.SUBSCRIBER_STAGE;

PUT 'file:///absolute/path/to/poc/nora-package/subscriber_operational_data.csv'
    @NORA_PACKAGE.SUBSCRIBER_STAGE
    AUTO_COMPRESS=FALSE
    OVERWRITE=TRUE;

COPY INTO NORA_PACKAGE.SUBSCRIBER_OPERATIONAL_DATA
FROM @NORA_PACKAGE.SUBSCRIBER_STAGE/subscriber_operational_data.csv
FILE_FORMAT = (
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

SELECT * FROM NORA_PACKAGE.SUBSCRIBER_OPERATIONAL_DATA ORDER BY subscriber_id;

-- Optional: use the table name below in the app env vars when Snowflake credentials are enabled.
-- SNOWFLAKE_OPERATIONAL_TABLE = NORA_PACKAGE.SUBSCRIBER_OPERATIONAL_DATA
