name: Build and Push to ACR

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        run: |
          az acr login --name rehnaacr
          
      - name: Build Docker image
        run: |
          docker build -t rehnaacr.azurecr.io/pythonapp:v1 .

      - name: Push Docker image
        run: |
          docker push rehnaacr.azurecr.io/pythonapp:v1
